# Generated by Django 6.0.2 on 2026-02-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('CENTRAL', 'central'), ('PROVENCIAL', 'provencial'), ('LOCAL', 'local'), ('WARD', 'ward')], max_length=16)),
                ('location_code', models.CharField(max_length=64, unique=True)),
                ('parent_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hierarchy.office')),
            ],
            options={
                'indexes': [models.Index(fields=['level'], name='hierarchy_o_level_7923d8_idx'), models.Index(fields=['location_code'], name='hierarchy_o_locatio_10a5d7_idx')],
            },
        ),
    ]
