# Generated by Django 6.0.2 on 2026-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='level',
            field=models.CharField(choices=[('CENTRAL', 'central'), ('PROVINCIAL', 'provincial'), ('LOCAL', 'local'), ('WARD', 'ward')], max_length=16),
        ),
    ]
