# Generated by Django 6.0.2 on 2026-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('CENTRAL_ADMIN', 'Central Admin'), ('CENTRAL_PROCUREMENT_STORE', 'Central Procurement/Store'), ('PROVINCIAL_ADMIN', 'Provincial Admin'), ('LOCAL_ADMIN', 'Local Admin'), ('WARD_OFFICER', 'Ward Officer'), ('FINANCE', 'Finance'), ('AUDIT', 'Audit')], max_length=225, null=True),
        ),
    ]
