# Generated by Django 6.0.2 on 2026-02-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0002_alter_office_level'),
        ('inventory', '0002_consumablestock_initial_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_date', models.DateField()),
                ('handover_condition', models.CharField(choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=16)),
                ('handover_letter', models.FileField(blank=True, null=True, upload_to='inventory/handover_letters/')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=16)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('GOOD', 'Good'), ('FAIR', 'Fair'), ('DAMAGED', 'Damaged')], max_length=16, null=True)),
                ('damage_photo', models.FileField(blank=True, null=True, upload_to='inventory/damage_photos/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_items', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_assignments', to='hierarchy.office')),
                ('assigned_to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_assignments', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='inventory.inventoryitem')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='actions_ite_status_1f17ad_idx'), models.Index(fields=['handover_date'], name='actions_ite_handove_a862d8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('assigned_to_user__isnull', False), ('assigned_to_office__isnull', False), _connector='OR'), name='item_assignment_target_required'), models.UniqueConstraint(condition=models.Q(('status', 'ASSIGNED')), fields=('item',), name='uniq_active_assignment_per_item')],
            },
        ),
    ]
