# Generated by Django 6.0.2 on 2026-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemassignment',
            name='assign_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
