# Generated by Django 6.0.2 on 2026-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablestock',
            name='initial_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='consumablestock',
            name='reorder_alert_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='inventory/invoices/'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
