# Generated by Django 6.0.2 on 2026-02-25 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_customfielddefinition_is_unique_and_more'),
        ('hierarchy', '0002_alter_office_level'),
        ('inventory', '0002_consumablestock_initial_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('STOCK_OUT', 'Stock Out'), ('DAMAGE', 'Damage'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('department', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='inventory/stock_transactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='currency',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='inventory/images/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('FIXED_ASSET', 'Fixed Asset'), ('CONSUMABLE', 'Consumable')], default='FIXED_ASSET', max_length=16),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pi_document',
            field=models.FileField(blank=True, null=True, upload_to='inventory/pi_documents/'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='project',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_document',
            field=models.FileField(blank=True, null=True, upload_to='inventory/warranty_documents/'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DISPOSED', 'Disposed'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned')], default='ACTIVE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_number'], name='inventory_i_item_nu_01b1d8_idx'),
        ),
        migrations.AddField(
            model_name='consumablestocktransaction',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumablestocktransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumablestocktransaction',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.consumablestock'),
        ),
        migrations.AddIndex(
            model_name='consumablestocktransaction',
            index=models.Index(fields=['stock', 'created_at'], name='inventory_c_stock_i_db0f9d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumablestocktransaction',
            index=models.Index(fields=['transaction_type'], name='inventory_c_transac_01d5ff_idx'),
        ),
    ]
