# Generated by Django 6.0.2 on 2026-02-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_consumablestock_initial_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ASSIGN', 'Assign'), ('RETURN', 'Return'), ('REPAIR', 'Repair'), ('DISPOSE', 'Dispose')], max_length=16)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
                ('remarks', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inventory/audit_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'created_at'], name='audit_inven_item_id_450cff_idx'), models.Index(fields=['action_type'], name='audit_inven_action__f63087_idx')],
            },
        ),
    ]
