# Generated by Django 6.0.2 on 2026-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='select_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('SELECT', 'Select'), ('FILE', 'File')], max_length=16),
        ),
    ]
